const QUESTION_COLLECTION = 'questions';
const QUIZ_COLLECTION = 'quizzes';
const QUESTION_BANK_COLLECTION = 'question-bank';
const HISTORY_COLLECTION = 'history';

export { QUIZ_COLLECTION, QUESTION_BANK_COLLECTION, QUESTION_COLLECTION, HISTORY_COLLECTION };
